### PR TITLE
Add driver for Sainsmart 16-channel USB-HID control

### PR DESCRIPTION
**Pull request by khilman**
First pass at adding support for the Sainsmart 16-channel USB-HID control module. Note that unlike the Sainsmart 4- and 8-channel which use FTDI GPIOs, this one uses USB-HID.

Signed-off-by: Kevin Hilman khilman@baylibre.com

### CODE REVIEW

**Comment by ondrej1024** [comment]
Thanks a lot for the source code to support this USB-HID control module. I can't test it because I don't have the card myself. I'm sure it works for you. But I would like to understand a little better the communication protocol which is used by that card. So from looking at your code I kind of _derived_ the following:

```
Read command:
  Request
  RD LN XX XX XX XX XX XX XX XX 'H' 'I' 'D' 'C' CS CS
  RD: read command (0xD2)
  LN: message length (excluding checksum)
  CS: checksum bytes (16 bits)
  XX: unknown meaning, probably don't care

  Response
  XX XX BM BM
  BM: Relay state bitmap (16 bits)
  XX: unknown meaning

Write command:
  Request
  WR LN BM BM XX XX XX XX XX XX 'H' 'I' 'D' 'C' CS CS
  WR: write command (0xC3)
  LN: message length (excluding checksum)
  BM: Relay state bitmap (16 bits)
  CS: checksum bytes (16 bits)
  XX: unknown meaning, probably don't care

  Response
  None

Relay State Bitmap:
   15  14  13  12  11  10   9   8   7   6   5   4   3   2   1   0    bits
  +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
  | 7 | 8 | 6 | 9 | 5 | 10| 4 | 11| 3 | 12| 2 | 13| 1 | 14| 0 | 15|  relay number
  +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
```

So it looks to me that both read and write request messages are exactly 16 bytes long. Probably we don't really need to send the remaining bytes which are in your read_cmd[] and write_cmd[] buffers. 
Based on these assumptions we can simplify the code a little. I will try to do this and then you might test it.

**Comment by khilman** [comment]
I tested locally by simply truncating read_cmd and write_cmd to 16
bytes, and it still works fine.

I updated the branch to reflect that.

Also note that the "Relay State Bitmap" is only "mapped" on the read side.  When writing, the relay number corresponds to the bit position.

**Comment by ondrej1024** [comment]
Thanks for testing the shorter message buffer.
Now I have modified the protocol implementation to reflect better the actual message structure. I have pushed your code and my changes on top to this branch in my repository:
[khilman-sain-usb-hid](https://github.com/ondrej1024/crelay/tree/khilman-sain-usb-hid)

Please have a look and test if possible. I'm curious to know if this works. I am also wondering about the 6 reserved bytes before the hid command signature. Do the values in there matter at all? Maybe you can experiment with this a bit. Thanks.

**Comment by khilman** [comment]
Your branch didn't quite work.  I fixed it up, and pushed a new branch.

**Pull request closed without merging**
