### PR TITLE
Add support for multiple boards; fix crash in crelay -i

### PR DESCRIPTION
**Pull request by derekatkins**
This patch both fixes a problem with crelay -i with a single sainsmart-16 board (it was crashing on me) and also adds support for multiple devices.  If you have multiple cards then you can list them via 'crelay -i' to get their serial numbers, and then you can use 'crelay -s <serial> ...' to control the relays on each device.

### CODE REVIEW

**Comment by ondrej1024** [comment]
Nice work Derek. Thanks for your contribution. I cannot test your modifications because I don't own this kind of card, so I have to rely on you to do all the necessary testing.
I haven't found a way to read the serial number from this Sainsmart relay card and I am not even sure  it has one. I noticed you are using the USB device path instead of the serial number in your patch which should be a good solution to distinguish currently connected cards. The drawback is that the association between the path and the actual card will change if the cards are unplugged and plugged in again in different order, I think.

**Comment by derekatkins** [comment]
Indeed, I don't know if it has a serial number.  The dmesg report says the following when I have two cards inserted:

```
[2181513.158027] usb 1-4: new full-speed USB device number 11 using xhci_hcd
[2181513.343880] usb 1-4: New USB device found, idVendor=0416, idProduct=5020
[2181513.343882] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[2181513.343884] usb 1-4: Product: HID Transfer
[2181513.343885] usb 1-4: Manufacturer: Nuvoton
[2181513.352124] input: Nuvoton HID Transfer as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:0416:5020.0003/input/input20
[2181513.352372] hid-generic 0003:0416:5020.0003: input,hidraw0: USB HID v1.10 Device [Nuvoton HID Transfer] on usb-0000:00:14.0-4/input0
[2181558.422269] usb 1-1: new full-speed USB device number 12 using xhci_hcd
[2181558.608138] usb 1-1: New USB device found, idVendor=0416, idProduct=5020
[2181558.608140] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[2181558.608142] usb 1-1: Product: HID Transfer
[2181558.608143] usb 1-1: Manufacturer: Nuvoton
[2181558.616398] input: Nuvoton HID Transfer as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:0416:5020.0004/input/input21
[2181558.616617] hid-generic 0003:0416:5020.0004: input,hidraw1: USB HID v1.10 Device [Nuvoton HID Transfer] on usb-0000:00:14.0-1/input0

```
I was hoping that the port name would be the unique location it was plugged into and not necessarily the order in which it was plugged.  Specifically, I know that the /devices path is definitely physical-port and not dependent on the plug-in order.  If it's using the input/hidraw0, input/hidraw1 then yeah, order might make a difference.  However I did not test whether the reported portname changed if I plugged the devices in in opposite order or in different ports.  I can try that later today if you wish?  Or maybe I can find a way to reference the underlying /devices path?

I did test that I was able to successfully flip relays in both devices via the command-line.  I did not test daemon mode.

Is there anything else you'd like me to test?

**Comment by ondrej1024** [comment]
> I was hoping that the port name would be the unique location it was plugged into and not necessarily the order in which it was plugged. 

You are right, the port name is associated to the physical USB port and does not change. I just tried this on my laptop. So I think this is a good way to identify the relay card connected to a certain port.

> I did test that I was able to successfully flip relays in both devices via the command-line. I did not test daemon mode.

Multiple relay card support is currently only implemented in command line mode. The WebGUI from daemon mode controls only the first detected relay. So no way to test this right now.

> Is there anything else you'd like me to test?

Can you post the output of the `crelay -i` command?

**Comment by derekatkins** [comment]
> Multiple relay card support is currently only implemented in command line mode. The WebGUI from daemon mode controls only the first detected relay. So no way to test this right now.

Okay.  Good to know that when I try to automate it I'll need to do something special instead of a simple REST API.

> Can you post the output of the `crelay -i` command?

Sure:

```
#crelay  -i

Detected relay cards:
  #1	Sainsmart USB-HID 16-channel relay card (serial 0001:000b:00)
  #2	Sainsmart USB-HID 16-channel relay card (serial 0001:000c:00)


```

Anything else?

**Comment by ondrej1024** [comment]
> Okay. Good to know that when I try to automate it I'll need to do something special instead of a simple REST API.

You  could give it a shot and try to add multiple cards support to the REST API. :smile:  You just need to add the handling of a new parameter for the serial number (function `process_http_request` in `crelay.c`). The WebGUI is more complicated but this can be done later.

**Comment by derekatkins** [comment]
> You could give it a shot and try to add multiple cards support to the REST API. smile You just need to add the handling of a new parameter for the serial number (function `process_http_request` in `crelay.c`). The WebGUI is more complicated but this can be done later.

Indeed, and I suspect I will look into that -- but of course that would be a different PR. :)

Thanks.

**Comment by ondrej1024** [comment]
I will merge this PR and release a new version of crelay. Thanks.

**Pull request merged**
