### PR TITLE
README file with IFTTT tutorial.

### PR DESCRIPTION
**Pull request by ImLunaUwU**
Just saving you some time.

### CODE REVIEW

**Comment by ondrej1024** [comment]
Thanks a lot for your contribution. The possibility of IFTTT integration is very interesting. Your instruction are quite simple, actually. 

However I would like to explore some more the functionality of the IFTTT service with regard to a secure connection. Opening the communication port to crelay in your firewall to the Internet is very dangerous. Anyone who knows your IP address and is able to use a port scanner can control your relays in the house. If this relay just switches on a table lamp this might not be a big issue but if it opens a valve for watering your garden or similar this is more serious. 

At the moment crelay has no authentication function implemented so this might be one thing that needs to be done.

**Comment by ImLunaUwU** [comment]
this is kinda a two part... ive made this too. https://github.com/MajorLOLGaming/crelay/blob/master/ifttt-warning.md

**Comment by ondrej1024** [comment]
Merged into master branch. I created a separate file for the tutorial.

**Comment by ImLunaUwU** [comment]
Okay, glad i could help.

**Pull request merged**
