### PR TITLE
Sain usb hid v2

### PR DESCRIPTION
**Pull request by khilman**

### CODE REVIEW

**Comment by khilman** [comment]
And yes, the reserved bytes seem to matter.  Especially on CMD_READ, if they're not all 0x1111, the read never returns.

**Comment by ondrej1024** [comment]
Thanks, looks great. If you have successfuIly tested it I think we can merge this. 
Just two comments. 
- line 109: please use the predefined uint16 type, as in the rest of the program
- line 132: should be just `*bitmap = mask;`

I would also like to rename the driver file into relay_drv_sainsmart16.c/.h. This is for consistency with the other file names which reflect the relay cards manufacturer. In case of HID API cards there is no known manufacturer, so I didn't follow this rule.

**Comment by ondrej1024** [comment]
I am also working on the getting the multiple cards support ready. For this to work we need a unique serial number from the card. Therefore it would be great if you could check if this card has a serial number assigned. Please check the iSerial property with lsusb, Thanks.

**Comment by ondrej1024** [comment]
@khilman : I did some [minor changes](https://github.com/ondrej1024/crelay/commit/eddd9e2fb9f15a4a5ee1b6bd48d7693e28ec0325) (mostly renaming) and pushed it to the [khilman-sain-usb-hid-v2 branch](https://github.com/ondrej1024/crelay/tree/khilman-sain-usb-hid-v2).
Could you please test this again and check that everything is working fine? Thanks a lot.

**Comment by khilman** [comment]
Hi Ondrej,

I'm away from my office this week attending Embedded Linux Conference so
don't have physical access to the relays.  I'll get back to you next
week.

Kevin

**Comment by khilman** [comment]
Updated and pushed a new sain-usb-hid-v3 based on yours, with only minor printf changes.

**Pull request closed without merging**
