### PR TITLE
Sainsmart device select

### PR DESCRIPTION
**Pull request by panarom**
I'm not sure this should be merged, because it's hacky, and only handles the command line mode for the sainsmart 4/8 relays; but I have 2 of those, so I need this functionality & figured I'd offer a contribution.

### CODE REVIEW

**Comment by ondrej1024** [comment]
Hi,
thanks for your contribution but multiple cards support has already been implemented in the `multiplecards_experimental` branch for command line mode. If would be great if you could test it with your cards and let me know if it works for you. Thanks.

**Comment by panarom** [comment]
HA, and it turns out somebody else already has a PR open for this. Seems like a popular feature ;-)

**Comment by ondrej1024** [comment]
Yes it has been requested before and it has been on my TODO list since the beginning of the project. The author of the original pull request seems to have lost interest so I completed the command line support for multiple cards myself. Now only the GUI support is missing. This is the latest feature I want to complete before going to version 1.0 of crelay.

**Comment by ondrej1024** [comment]
Did you try if the `multiplecards_experimental` branch works with your 2 Sainsmart cards ? 
First try the `-i` option to check if both cards are listed and then try to control them by specifying the serial number with the `-s` option. Please report the result.

**Comment by panarom** [comment]
I'll give that a try and let you know

**Comment by panarom** [comment]
-i detected both cards, and I was able to operate both independently with the -s flag.
Closing PR

**Pull request closed without merging**
